### PR TITLE
Support no_std environment

### PR DESCRIPTION
**Pull request by tnishinaga**
Thank you for creating such a great library!

I fixed this library to be able to build for the no_std environment.

Could you check this PR?

### CODE REVIEW

**Review by Yatekii — APPROVED** [review]
Thanks a lot for the good words and the work =)

This is a great addition! Tho I fear the tables will use up quite some space on your MCU if you include them all?

**Comment by tnishinaga** [comment]
> Tho I fear the tables will use up quite some space on your MCU if you include them all?

Indeed, the [CODES](https://github.com/Yatekii/jep106/blob/master/src/codes.rs#L1) is large, about 60 KB in size.
However, since there is a lot of ROM space in modern microcontrollers(e.g. Raspberry Pi Pico has 2MB of Flash ROM), it is probably ok ;-)

**Comment by Yatekii** [comment]
Yeah :) Maybe there is possibilities to compact the sparse data. But also maybr not worth the effort. What are you using it for if I may ask?

**Comment by tnishinaga** [comment]
Now I am creating a toy jtag debugger that works on a microcontroller.
This crate will be used for that project.
https://github.com/tnishinaga/OdangoOCDS/tree/initial_release_working

**Pull request merged**
